annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - bump version of VM components to [v1.109.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.109.1)
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-agent
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/vmagent
    - name: Changelog
      url: https://docs.victoriametrics.com/changelog
apiVersion: v2
appVersion: v1.109.1
dependencies:
- name: victoria-metrics-common
  repository: https://victoriametrics.github.io/helm-charts
  version: 0.0.*
description: Victoria Metrics Agent - collects metrics from various sources and stores
  them to VictoriaMetrics
home: https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
keywords:
- victoriametrics
- vmagent
- agent
- collector
- monitoring
- kubernetes
- observability
- metrics
- timeseries
- servicediscovery
kubeVersion: '>=1.25.0-0'
name: victoria-metrics-agent
sources:
- https://github.com/VictoriaMetrics/helm-charts
type: application
version: 0.15.5
