annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - bump version of VM components to [v1.109.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.109.1)
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-auth
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/vmauth
    - name: Changelog
      url: https://docs.victoriametrics.com/changelog
apiVersion: v2
appVersion: v1.109.1
dependencies:
- name: victoria-metrics-common
  repository: https://victoriametrics.github.io/helm-charts
  version: 0.0.*
description: Victoria Metrics Auth - is a simple auth proxy and router for VictoriaMetrics.
home: https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
keywords:
- victoriametrics
- vmauth
- auth
- proxy
- router
- balancer
- monitoring
- kubernetes
- observability
- metrics
- timeseries
kubeVersion: '>=1.25.0-0'
name: victoria-metrics-auth
sources:
- https://github.com/VictoriaMetrics/helm-charts
type: application
version: 0.8.5
